/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import java.util.ArrayList;
import entities.Dados;
import entities.Paciente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bismarck
 */
public class Triagem extends javax.swing.JFrame {
    String botao;
    /**
     * Creates new form Triagem
     */
    public Triagem() {
        initComponents();
        CarregarTabelaPacientes();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        ArrayList<Paciente> pacientes = Dados.getListaPacientes();
        // Desabilitando botões
        btnNewPatient.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(false);
        btnSearch.setEnabled(true);
        btnCancel.setEnabled(false);
        
        //Desabilitar caixas de texto
        txtName.setEnabled(false);
        ftxtCPF.setEnabled(false);
        ftxtBirthDate.setEnabled(false);
        ftxtTelefone.setEnabled(false);
        ftxtEmail.setEnabled(false);
        ftxtCEP.setEnabled(false);
        ftxtCadUnico.setEnabled(false);
    }
    
    //Carregar a tabela de Pacientes
    public void CarregarTabelaPacientes(){
        ArrayList<Paciente> pacientes = Dados.getListaPacientes();
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome","CPF","Data de Nascimento", "Telefone", "E-mail", "CEP", "CadUnico"},0 );
        for (int i = 0; i < pacientes.size(); i++) {
            Object line[] = new Object[]{pacientes.get(i).getNome(), 
            pacientes.get(i).getCpf(), pacientes.get(i).getDataNacimento(),
            pacientes.get(i).getTelefone(), pacientes.get(i).getEmail(),
            pacientes.get(i).getCep(), pacientes.get(i).getCadastroUnico()};
            
            modelo.addRow(line);
        }
        tblDados.setModel(modelo);
        tblDados.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblDados.getColumnModel().getColumn(1).setPreferredWidth(20);
        tblDados.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblDados.getColumnModel().getColumn(3).setPreferredWidth(30);
        tblDados.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblDados.getColumnModel().getColumn(5).setPreferredWidth(20);
        tblDados.getColumnModel().getColumn(6).setPreferredWidth(20);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewPatient = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        ftxtTelefone = new javax.swing.JFormattedTextField();
        ftxtEmail = new javax.swing.JFormattedTextField();
        ftxtCEP = new javax.swing.JFormattedTextField();
        ftxtBirthDate = new javax.swing.JFormattedTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        ftxtCadUnico = new javax.swing.JFormattedTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Triagem");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_window.png")).getImage());

        btnNewPatient.setText("Novo Paciente");
        btnNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPatientActionPerformed(evt);
            }
        });

        btnDelete.setText("Excluir");

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Data de Nascimento", "Telefone", "E-mail", "CEP", "CadUnico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDados);
        if (tblDados.getColumnModel().getColumnCount() > 0) {
            tblDados.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblDados.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblDados.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblDados.getColumnModel().getColumn(3).setPreferredWidth(30);
            tblDados.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblDados.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblDados.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        btnSearch.setText("Pesquisar");

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Nome:");

        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCPF.setText("CPF:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("D. de Nacimento:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Telefone:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("E-mail:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CEP:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CadÚnico:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        try {
            ftxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtBirthDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtCadUnico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNewPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ftxtCadUnico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtCadUnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewPatient)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit)
                    .addComponent(btnSearch)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPatientActionPerformed
        botao = "novo";
        // Habilitando novos botões
        btnNewPatient.setEnabled(false);
        btnCancel.setEnabled(true);
        btnSave.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
        btnSearch.setEnabled(true);
        
        //Habilitando campos de texto
        txtName.setEnabled(true);
        ftxtCPF.setEnabled(true);
        ftxtBirthDate.setEnabled(true);
        ftxtTelefone.setEnabled(true);
        ftxtEmail.setEnabled(true);
        ftxtCEP.setEnabled(true);
        ftxtCadUnico.setEnabled(true);
        
        //Setando os campos como string vazia
        txtName.setText("");
        ftxtCPF.setText("");
        ftxtBirthDate.setText("");
        ftxtTelefone.setText("");
        ftxtEmail.setText("");
        ftxtCEP.setText("");
        ftxtCadUnico.setText("");
    }//GEN-LAST:event_btnNewPatientActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       // ArrayList<Paciente> pacientes = Dados.getListaPacientes();
        // TODO add your handling code here:        
        String nome = txtName.getText();
        String cpf = ftxtCPF.getText();
        String dataNascimento = ftxtBirthDate.getText();
        String telefone = ftxtTelefone.getText();
        String email = ftxtEmail.getText();
        String cep = ftxtCEP.getText();
        String cadUnico = ftxtCadUnico.getText();
        
        if (txtName.getText().equals("") ||
             ftxtCPF.getText().equals("") ||
             ftxtBirthDate.getText().equals("")||
             ftxtTelefone.getText().equals("") ||
             ftxtEmail.getText().equals("") ||
             ftxtCEP.getText().equals("") ||
             ftxtCadUnico.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
            
        }
        else{ 
            //Salvar
            if(botao.equals("novo")){
                Paciente paciente = new Paciente(nome, dataNascimento, email, cpf, cep, telefone, cadUnico);
                Dados.adicionarPaciente(paciente);
                JOptionPane.showMessageDialog(null,"Novo paciente adicionado!", "Novo paciente", JOptionPane.INFORMATION_MESSAGE);
            }
            //Editar
            else if(botao.equals("editar")){
                int indice = tblDados.getSelectedRow();
                
                Dados.getListaPacientes().get(indice).setNome(nome);
                Dados.getListaPacientes().get(indice).setCpf(cpf);
                Dados.getListaPacientes().get(indice).setDataNacimento(dataNascimento);
                Dados.getListaPacientes().get(indice).setTelefone(telefone);
                Dados.getListaPacientes().get(indice).setEmail(email);
                Dados.getListaPacientes().get(indice).setCep(cep);
                Dados.getListaPacientes().get(indice).setCadastroUnico(cadUnico);
                
            }
            // Desabilitando botões
            btnNewPatient.setEnabled(true);
            btnEdit.setEnabled(false);
            btnDelete.setEnabled(false);
            btnSave.setEnabled(false);
            btnSearch.setEnabled(true);
            btnCancel.setEnabled(false);
        
            //Desabiliatar caixas de texto
            txtName.setEnabled(false);
            ftxtCPF.setEnabled(false);
            ftxtBirthDate.setEnabled(false);
            ftxtTelefone.setEnabled(false);
            ftxtEmail.setEnabled(false);
            ftxtCEP.setEnabled(false);
            ftxtCadUnico.setEnabled(false);
        }       

        
        //Carregar os Dados do paciente para a tabela
        CarregarTabelaPacientes();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        // Desabilitando botões
        btnNewPatient.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(false);
        btnSearch.setEnabled(true);
        btnCancel.setEnabled(false);
        
        //Habiliatar caixas de texto
        txtName.setEnabled(false);
        ftxtCPF.setEnabled(false);
        ftxtBirthDate.setEnabled(false);
        ftxtTelefone.setEnabled(false);
        ftxtEmail.setEnabled(false);
        ftxtCEP.setEnabled(false);
        ftxtCadUnico.setEnabled(false);
        
        //Setando os campos como string vazia
        txtName.setText("");
        ftxtCPF.setText("");
        ftxtBirthDate.setText("");
        ftxtTelefone.setText("");
        ftxtEmail.setText("");
        ftxtCEP.setText("");
        ftxtCadUnico.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        botao = "editar";
        // Desabilitando botões
        btnNewPatient.setEnabled(false);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnSave.setEnabled(true);
        btnSearch.setEnabled(false);
        btnCancel.setEnabled(true);
        
        //Desabilitar caixas de texto
        txtName.setEnabled(true);
        ftxtCPF.setEnabled(true);
        ftxtBirthDate.setEnabled(true);
        ftxtTelefone.setEnabled(true);
        ftxtEmail.setEnabled(true);
        ftxtCEP.setEnabled(true);
        ftxtCadUnico.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDadosMouseClicked
        // TODO add your handling code here:
        int i = tblDados.getSelectedRow();
        //JOptionPane.showMessageDialog(null,"Clicou na Tabela", "Tetse", JOptionPane.INFORMATION_MESSAGE);
        if(i <= Dados.getListaPacientes().size()){
            //JOptionPane.showMessageDialog(null,"Entrou no if", "Tetse", JOptionPane.INFORMATION_MESSAGE);
            Paciente patient = Dados.getListaPacientes().get(i);
            txtName.setText(String.valueOf(patient.getNome()));
            ftxtCPF.setText(String.valueOf(patient.getCpf()));
            ftxtBirthDate.setText(String.valueOf(patient.getDataNacimento()));
            ftxtTelefone.setText(String.valueOf(patient.getTelefone()));
            ftxtEmail.setText(String.valueOf(patient.getEmail()));
            ftxtCEP.setText(String.valueOf(patient.getCep()));
            ftxtCadUnico.setText(String.valueOf(patient.getCadastroUnico()));
            
            // Desabilitando botões
            btnNewPatient.setEnabled(true);
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            btnSave.setEnabled(false);
            btnSearch.setEnabled(true);
            btnCancel.setEnabled(false);
        
            //Desabilitar caixas de texto
            txtName.setEnabled(false);
            ftxtCPF.setEnabled(false);
            ftxtBirthDate.setEnabled(false);
            ftxtTelefone.setEnabled(false);
            ftxtEmail.setEnabled(false);
            ftxtCEP.setEnabled(false);
            ftxtCadUnico.setEnabled(false);
        }
    }//GEN-LAST:event_tblDadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNewPatient;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JFormattedTextField ftxtBirthDate;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtCadUnico;
    private javax.swing.JFormattedTextField ftxtEmail;
    private javax.swing.JFormattedTextField ftxtTelefone;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
